name: Gitleaks Secret Scan - my

on:
  workflow_dispatch:

jobs:
  gitleaks-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Gitleaks
      run: |
        curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.28.0/gitleaks_8.28.0_linux_x64.tar.gz -o gitleaks.tar.gz
        tar -xzf gitleaks.tar.gz -C gitleaks-bin
        sudo mv gitleaks-bin/gitleaks /usr/local/bin/
        gitleaks version

    - name: Run Gitleaks scan
      run: |
        gitleaks detect --source . --verbose --report-path gitleaks-report.json

    - name: Upload Gitleaks Report (Optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: gitleaks-report
        path: gitleaks-report.json
